### ISSUE TITLE
Seabug depends on `release.nix` but it was removed

### ISSUE THREAD

**Issue by rynoV** [mlabs-haskell/nft-marketplace-server#35]
Just realized seabug depends on the `release.nix` file, see [here](https://github.com/mlabs-haskell/seabug/blob/901412826d31bc48b571b076ce7c37a514a49c08/arion-compose.nix#L4), #34 removed it though.

**Comment by rynoV** [comment]
cc @t4ccer , will we just add it back, or is there a better way to do what `release.nix` was doing?

**Comment by t4ccer** [comment]
Oh seabug isn't flakified yet, copy `default.nix` from ODC to here and use it in the same way

**Comment by rynoV** [comment]
I copied the `default.nix` from ODC and updated that line in `arion-compose.nix` to point reference `default.nix` instead of `release.nix` getting an error:

```
error: 'functionArgs' requires a function

       at /nix/store/1i9xy4a7dnyr4binxz17kda79n48ayxb-nixpkgs/nixpkgs/lib/trivial.nix:443:10:

          442|     then f.__functionArgs or (lib.functionArgs (f.__functor f))
          443|     else builtins.functionArgs f;
             |          ^
          444|
```

No idea about this, and the previous version is working, so I'm going to leave this for now

**Comment by t4ccer** [comment]
Push it to some branch, I'll look into it

**Comment by rynoV** [comment]
Sure:

https://github.com/mlabs-haskell/nft-marketplace-server/tree/calum/35-replace-release-nix
https://github.com/mlabs-haskell/seabug/tree/calum/update-nft-marketplace-server

**Comment by t4ccer** [comment]
I've pushed one commit to https://github.com/mlabs-haskell/seabug/tree/calum/update-nft-marketplace-server

**Comment by rynoV** [comment]
Oops yeah my bad, should have figured to do that!

**Comment by rynoV** [comment]
@t4ccer I tried that change and I'm still getting the same error

**Comment by t4ccer** [comment]
I would swear it worked before... Try now please

**Comment by rynoV** [comment]
That works now, thanks! I'll open PRs
